min_column_spacing: 3
validate_xml: true
auto_use_Med_item_reader: true
warn_on_auto_use_Med_item_reader: true
allow_overwriting: false
markables_type_filter: ident_or_bridge
markables_level_filter: reference
conll_extension: .conll
words_dir: Basedata
words_files_extension: _words.xml
markables_dir: Markables
markables_files_extension: _coref_level.xml
log_on_error: false
dirs_to_ignore:
    - Configuration

conll_defaults:
    document_id: UNKNOWN
    part_number: 0
    word_number: '[WORD_NUMBER]'
    word: '[WORD]'
    POS: '[POS]'
    parse_bit: '*'
    pred_lemma: '-'
    pred_frameset_ID: '-'
    word_sense: '-'
    speaker: UNKNOWN
    named_entities: '*'
    coref: '-'

on_missing:
    document_id: throw
    part_number: nothing
    word_number: throw
    word: throw
    POS: nothing
    parse_bit: nothing
    pred_lemma: nothing
    pred_frameset_ID: nothing
    word_sense: nothing
    speaker: nothing
    named_entities: nothing
    coref: nothing
