# Data processing
validate_xml: true
coref_type_filter: ident_or_bridge
coref_level_filter: reference

# Reporting
allow_overwriting: false
log_on_error: true
auto_use_Med_item_reader: true
warn_on_auto_use_Med_item_reader: false

# MMAX
basedata_dir: Basedata
markables_dir: Markables
words_files_extension: _words.xml
coref_files_extension: _coref_level.xml
sentences_files_extension: null
dirs_to_ignore:
    - Configuration

# CoNLL
conll_extension: .conll
min_column_spacing: 3

on_missing:
    document_id: throw
    part_number: nothing
    word_number: throw
    word: throw
    POS: nothing
    parse_bit: nothing
    pred_lemma: nothing
    pred_frameset_ID: nothing
    word_sense: nothing
    speaker: nothing
    named_entities: nothing
    coref: nothing

conll_defaults:
    document_id: UNKNOWN
    part_number: 0
    word_number: '[WORD_NUMBER]'
    word: '[WORD]'
    POS: '[POS]'
    parse_bit: '*'
    pred_lemma: '-'
    pred_frameset_ID: '-'
    word_sense: '-'
    speaker: UNKNOWN
    named_entities: '*'
    coref: '-'
