# Data processing
validate_xml: true

# Reporting
allow_overwriting: false
log_on_error: true

# MMAX
basedata_dir: Basedata
markables_dir: Markables
words_files_extension: _words.xml
dirs_to_ignore:
    - Configuration

# Raw
raw_extension: .txt
